server:
  port: 8222

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/changliulab?serverTimezone=GMT%2B8
    username: root
    password: Changliulab@2022
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/changliulab?serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/changliulab?serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/changliulab?serverTimezone=GMT%2B8
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 1800000
      lettuce:
        pool:
          max-active: 4
          max-wait: -1
          max-idle: 2
          min-idle: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    host: 119.12.172.94
    port: 25
    username: info
    password: changliu@2022mail
    protocol: smtp
    properties:
      mail:
        transport.protocol: smtp
        smtp:
          auth: true
  application:
    name: changliulab
alibaba:
  cloud:
    oss:
      endpoint: oss-cn-beijing.aliyuncs.com
    secret-key: 84bk2feP4w5Zp2w0OaPBITCxpB22RH
    access-key: LTAI5tRT1D7wKyS6PZWM1zzq
    bucket-name: changliulab
jwt:
  token:
    key: "a264pq//klcJzM6dq8fcYqyDRqXwKqvn2LhxiCyd08LilpiitYD1XiY9BqN2ysB0dUQ2i5Z/l8s5YQdJG/DNJA=="
mybatis-plus:
  mapper-locations: classpath:com/venson/changliulabstandalone/mapper/xml/*.xml
logging:
  file:
    path: /var/log/changliulab
  level:
    root: info
